# Site settings
name: Cтрельченко Александр
description: ""
url: "http://alekstore.info/about/"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  dashingcode
codepen_username: your_codepen_username_goes_here
facebook_username: your_facebook_username_goes_here
vk_username: your_vk_username_goes_here
twitter_username: your_twitter_username_goes_here
#sites_google_username: your_sites_google_username_goes_here
# linkedin_username: your_linked_in_username_goes_here
# vine_username:  your_vine_username_goes_here
instagram_username:  your_instagram_username_goes_here
# flickr_username: your_flickr_username_goes_here
# steam_username: your_steam_username_goes_here
# soundcloud_username:  your_soundcloud_username_goes_here
# stack_of_username: your_stack_overflow_account_id_number_goes_here
# reddit_username: your_reddit_username_goes_here
# medium_username:  your_medium_username_goes_here
# tumblr_username: your_tumblr_username_goes_here
# weibo_username: your_weibo_username_goes_here
# lastfm_username: your_lastfm_username_goes_here
blog_url: "/blog"
email: aleksandr@strelchenko.ml
# public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
avatar_img_path: "imgs/xx480_sasha_icon.gif"
# avatar_img_path: "imgs/avatar.jpg"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
# avatar_img_path: https://drive.google.com/open?id=1_SMnvmMgwvRWWfvnQX0_ys8gRwYvQUHE


front_img: yes
front_img_path: "imgs/bg2.jpg"
# front_img_path: "imgs/background.jpg"
# front_img_path: https://drive.google.com/open?id=1tJ1OEhmfPqtnk_XVL0S3iirZ4ssQJHns


favicon_img: yes
favicon_img_path: "imgs/60x60_icon.png"
# favicon_img_path: "imgs/favicon.ico"
# favicon_img_path: https://drive.google.com/open?id=1DcAEjMAJxxRZka0oB4VsHmI4l31JX0K5


# Build settings
markdown: kramdown
permalink: pretty
